ovh:
  endpoint: 'ovh-ca'
  appKey: ''
  appSecret: ''
  consumerKey: ''

webhook:
  webhookURL: "https://discord.com/api/webhooks/.."

ips:
  - ipAddress: "51.222.259.125"
    checkInterval: 30s

messages:
#The message format must be a valid JSON embed format. 
  mitigation-enabled:
    title: "DDoS Attack detected!"
    description: "\nIP `{ipAddress}` have mitigation mode enabled!"
    color: 16711680 # You can use this website to convert HEXadecimal numbers to decimal numbers: https://www.rapidtables.com/convert/number/hex-to-decimal.html
  mitigation-disabled:
    title: "Seems that the DDoS attack has stopped!"
    description: "\nIP `{ipAddress}` is no longer under mitigation mode!"
    color: 65280 # You can use this website to convert HEXadecimal numbers to decimal numbers: https://www.rapidtables.com/convert/number/hex-to-decimal.html